name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Swift packages
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    
    - name: Build and test
      run: |
        make build
        make test
    
    - name: Lint code
      run: make lint

  build-release:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Swift packages
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    
    - name: Build release
      run: make build-release
    
    - name: Sign and verify
      run: |
        make sign
        make verify
    
    - name: Test release binary
      run: make test-release
    
    - name: Create archive
      run: make archive
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: transcriber-release
        path: releases/
        retention-days: 30